-- 04_ingreso_egreso.sql
-- Datos ficticios, sin tildes ni ñ, FK por subconsulta

INSERT INTO ingreso (id_paciente, id_unidad_medica, id_servicio, id_medico, id_recurso, fecha_hora, motivo_ingreso, diagnostico_presuntivo) VALUES
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Emergencias'), (SELECT id_servicio FROM servicio_unidad WHERE nombre = 'Unidad de Cuidado Critico de Adultos'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Alejandro Morales'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'CML-QTZ-E01'), '2026-01-10 08:30:00', 'Dolor toracico intenso', 'Infarto agudo de miocardio'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Cirugia'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dr. Roberto Castillo'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'QF-QTZ-01'), '2026-01-11 14:00:00', 'Apendicitis aguda', 'Apendicitis aguda complicada'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0005'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Emergencias'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dra. Elena Vargas'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'CML-QTZ-E02'), '2026-01-12 22:15:00', 'Traumatismo craneoencefalico', 'Contusion cerebral leve'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Hospitalizacion'), (SELECT id_servicio FROM servicio_unidad WHERE nombre = 'Medicina Interna'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Carlos Mendez'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'CML-QTZ-H01'), '2026-01-13 09:00:00', 'Infeccion respiratoria', 'Neumonia adquirida en la comunidad'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0009'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Emergencias'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dra. Lucia Herrera'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'CML-SMR-E01'), '2026-02-05 18:45:00', 'Fiebre alta y convulsion', 'Convulsion febril'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0010'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Hospitalizacion'), (SELECT id_servicio FROM servicio_unidad WHERE nombre = 'Pediatria'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Patricia Molina'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'CML-SMR-H02'), '2026-02-06 07:30:00', 'Deshidratacion severa', 'Gastroenteritis aguda'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0012'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Cirugia'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dr. Julio Ramirez'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'QF-SMR-02'), '2026-02-07 11:00:00', 'Tumor mamario', 'Carcinoma ductal'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0014'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Hospitalizacion'), (SELECT id_servicio FROM servicio_unidad WHERE nombre = 'Neurologia'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Fernanda Diaz'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'CML-HUE-H01'), '2026-02-10 15:00:00', 'Accidente cerebrovascular', 'ACV isquemico'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Emergencias'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dr. Mario Gutierrez'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'CML-HUE-E01'), '2026-03-01 03:20:00', 'Dolor abdominal agudo', 'Pancreatitis aguda'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0018'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Cirugia'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dra. Carmen Aguilar'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'QF-HUE-01'), '2026-03-02 10:30:00', 'Fractura de femur', 'Fractura cerrada de femur'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0020'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Hospitalizacion'), (SELECT id_servicio FROM servicio_unidad WHERE nombre = 'Unidad de Cuidados Intermedios'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Marisol Pineda'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'CML-QTZ-H03'), '2026-03-05 20:00:00', 'Insuficiencia respiratoria', 'Distres respiratorio'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0022'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Emergencias'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dr. Pedro Alvarez'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'CML-SMR-E03'), '2026-03-08 07:00:00', 'Hemorragia digestiva alta', 'Ulcera peptica sangrante'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0023'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Hospitalizacion'), (SELECT id_servicio FROM servicio_unidad WHERE nombre = 'Oncologia'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Ricardo Estrada'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'CML-QTZ-H05'), '2026-03-10 12:00:00', 'Quimioterapia', 'Leucemia mieloide aguda'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0024'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Cirugia'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dra. Gabriela Luna'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'QF-QTZ-03'), '2026-03-15 16:45:00', 'Cesarea programada', 'Embarazo a termino'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0025'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Emergencias'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dr. Oscar Vega'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'CML-HUE-E05'), '2026-04-02 09:10:00', 'Trauma abdominal', 'Contusion abdominal'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0013'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Emergencias'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dr. Jorge Luis Fuentes'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'CML-SMR-E05'), '2026-04-05 21:30:00', 'Dolor lumbar intenso', 'Lumbalgia mecanica'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0017'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Hospitalizacion'), (SELECT id_servicio FROM servicio_unidad WHERE nombre = 'Unidad de Cuidado Critico de Adultos'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Eduardo Salazar'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'CML-HUE-H06'), '2026-04-08 06:00:00', 'Sepsis grave', 'Sepsis por neumonia'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0011'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Hospitalizacion'), (SELECT id_servicio FROM servicio_unidad WHERE nombre = 'Pediatria'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Ana Maria Torres'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'CML-SMR-H04'), '2026-04-10 11:15:00', 'Asfixia perinatal', 'Hipoxia neonatal');

INSERT INTO egreso (id_ingreso, id_unidad_medica, id_servicio, id_medico, id_recurso, fecha_hora, diagnostico_principal, motivo_egreso, codigo_egreso, egreso_sin_consentimiento, motivo_sin_consentimiento, numero_dias_hospitalizado, id_hospital_referido) VALUES
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001') AND fecha_hora = '2026-01-10 08:30:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Emergencias'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dr. Alejandro Morales'), NULL, '2026-01-15 10:00:00', 'Infarto agudo de miocardio', 'Alta por mejoria', 'Vivo', FALSE, NULL, 5, NULL),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003') AND fecha_hora = '2026-01-11 14:00:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Cirugia'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dr. Roberto Castillo'), NULL, '2026-01-13 08:00:00', 'Apendicitis aguda complicada', 'Alta quirurgica', 'Vivo', FALSE, NULL, 2, NULL),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0005') AND fecha_hora = '2026-01-12 22:15:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Emergencias'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dra. Elena Vargas'), NULL, '2026-01-14 07:00:00', 'Contusion cerebral leve', 'Alta voluntaria sin consentimiento', 'Vivo', TRUE, 'Paciente solicito salida antes de alta medica', 2, NULL),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007') AND fecha_hora = '2026-01-13 09:00:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Hospitalizacion'), (SELECT id_servicio FROM servicio_unidad WHERE nombre = 'Medicina Interna'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Carlos Mendez'), NULL, '2026-01-20 11:30:00', 'Neumonia adquirida en la comunidad', 'Alta por mejoria', 'Vivo', FALSE, NULL, 7, NULL),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0009') AND fecha_hora = '2026-02-05 18:45:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Emergencias'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dra. Lucia Herrera'), NULL, '2026-02-06 09:00:00', 'Convulsion febril', 'Alta', 'Vivo', FALSE, NULL, 1, NULL),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0010') AND fecha_hora = '2026-02-06 07:30:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Hospitalizacion'), (SELECT id_servicio FROM servicio_unidad WHERE nombre = 'Pediatria'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Patricia Molina'), NULL, '2026-02-09 14:00:00', 'Gastroenteritis aguda', 'Alta', 'Vivo', FALSE, NULL, 3, NULL),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0012') AND fecha_hora = '2026-02-07 11:00:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Cirugia'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dr. Julio Ramirez'), NULL, '2026-02-14 10:00:00', 'Carcinoma ductal', 'Alta quirurgica', 'Vivo', FALSE, NULL, 7, NULL),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0014') AND fecha_hora = '2026-02-10 15:00:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Hospitalizacion'), (SELECT id_servicio FROM servicio_unidad WHERE nombre = 'Neurologia'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Fernanda Diaz'), NULL, '2026-02-25 16:00:00', 'ACV isquemico', 'Fallecimiento durante hospitalizacion', 'Muerto', TRUE, 'Familia rechaza procedimientos adicionales', 15, NULL),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016') AND fecha_hora = '2026-03-01 03:20:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Emergencias'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dr. Mario Gutierrez'), NULL, '2026-03-05 11:00:00', 'Pancreatitis aguda', 'Alta', 'Vivo', FALSE, NULL, 4, NULL),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0018') AND fecha_hora = '2026-03-02 10:30:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Cirugia'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dra. Carmen Aguilar'), NULL, '2026-03-04 09:00:00', 'Fractura cerrada de femur', 'Alta quirurgica', 'Vivo', FALSE, NULL, 2, NULL),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0020') AND fecha_hora = '2026-03-05 20:00:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Hospitalizacion'), (SELECT id_servicio FROM servicio_unidad WHERE nombre = 'Unidad de Cuidados Intermedios'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Marisol Pineda'), NULL, '2026-03-08 08:00:00', 'Distres respiratorio', 'Alta', 'Vivo', FALSE, NULL, 3, NULL),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0024') AND fecha_hora = '2026-03-15 16:45:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Cirugia'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dra. Gabriela Luna'), NULL, '2026-03-16 12:00:00', 'Embarazo a termino', 'Alta por parto', 'Parto', FALSE, NULL, 1, NULL),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0025') AND fecha_hora = '2026-04-02 09:10:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Emergencias'), NULL, (SELECT id_medico FROM medico WHERE nombre = 'Dr. Oscar Vega'), NULL, '2026-04-04 07:00:00', 'Contusion abdominal', 'Alta', 'Vivo', TRUE, 'Paciente abandona tratamiento', 2, NULL),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0023') AND fecha_hora = '2026-03-10 12:00:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Hospitalizacion'), (SELECT id_servicio FROM servicio_unidad WHERE nombre = 'Oncologia'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Ricardo Estrada'), NULL, '2026-03-18 10:00:00', 'Leucemia mieloide aguda', 'Alta por remision', 'Vivo', FALSE, NULL, 8, NULL);

INSERT INTO diagnostico_secundario (id_egreso, descripcion) VALUES
((SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001') AND fecha_hora = '2026-01-10 08:30:00')), 'Hipertension arterial controlada'),
((SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001') AND fecha_hora = '2026-01-10 08:30:00')), 'Diabetes mellitus tipo 2'),
((SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0005') AND fecha_hora = '2026-01-12 22:15:00')), 'Hipertension arterial'),
((SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007') AND fecha_hora = '2026-01-13 09:00:00')), 'EPOC leve'),
((SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0014') AND fecha_hora = '2026-02-10 15:00:00')), 'Anemia por deficiencia'),
((SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0020') AND fecha_hora = '2026-03-05 20:00:00')), 'Asma bronquial');
