-- 05_consulta_externa.sql
-- Datos ficticios, sin tildes ni ñ, FK por subconsulta

INSERT INTO cita_programada (id_paciente, id_medico, id_clinica, fecha_hora, estado, referida_por_institucion, notificada_cancelacion) VALUES
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Alejandro Morales'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-01-QTZ'), '2026-01-20 09:00:00', 'Realizada', FALSE, NULL),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0002'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Elena Vargas'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-01-SMR'), '2026-01-22 10:30:00', 'Realizada', FALSE, NULL),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Carlos Mendez'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-03-QTZ'), '2026-02-01 08:00:00', 'Programada', TRUE, FALSE),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0004'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Lucia Herrera'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-04-QTZ'), '2026-02-03 11:15:00', 'Realizada', FALSE, NULL),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0005'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Roberto Castillo'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-05-QTZ'), '2026-02-10 14:00:00', 'Reprogramada', FALSE, TRUE),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0006'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Patricia Molina'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-01-SMR'), '2026-02-12 16:30:00', 'Realizada', FALSE, NULL),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Julio Ramirez'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-02-SMR'), '2026-02-15 09:00:00', 'Realizada', FALSE, NULL),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0008'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Fernanda Diaz'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-03-SMR'), '2026-02-18 11:00:00', 'Cancelada', FALSE, TRUE),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0015'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Mario Gutierrez'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-04-SMR'), '2026-02-20 13:30:00', 'Programada', FALSE, NULL),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Carmen Aguilar'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-05-SMR'), '2026-02-25 08:30:00', 'Realizada', TRUE, FALSE),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0019'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Pedro Alvarez'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-01-HUE'), '2026-03-01 10:00:00', 'Realizada', FALSE, NULL),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0020'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Ana Maria Torres'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-03-HUE'), '2026-03-05 15:00:00', 'Realizada', FALSE, NULL),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0021'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Jorge Luis Fuentes'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-05-HUE'), '2026-03-07 09:00:00', 'Reprogramada', FALSE, TRUE),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0024'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Beatriz Rojas'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-02-HUE'), '2026-03-09 11:30:00', 'Realizada', TRUE, FALSE),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0025'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Eduardo Salazar'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-04-HUE'), '2026-03-12 14:00:00', 'Programada', FALSE, NULL);

INSERT INTO consulta (id_cita, id_paciente, id_medico, id_clinica, fecha, tipo_consulta, diagnostico, otros_datos_interes, notas_observaciones, costo) VALUES
((SELECT id_cita FROM cita_programada WHERE fecha_hora = '2026-01-20 09:00:00'), (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Alejandro Morales'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-01-QTZ'), '2026-01-20', 'Primera vez', 'Hipertension arterial esencial', 'Presion 160/100', 'Seguimiento mensual recomendado', 250.00),
((SELECT id_cita FROM cita_programada WHERE fecha_hora = '2026-01-22 10:30:00'), (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0002'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Elena Vargas'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-01-SMR'), '2026-01-22', 'Primera vez', 'Rinitis alergica', 'Sintomas estacionales', 'Uso de antihistaminicos', 250.00),
(NULL, (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Carlos Mendez'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-03-QTZ'), '2026-02-01', 'Referida', 'Convulsion febril', 'Referencia de pediatria', 'Referido por pediatra', 200.00),
((SELECT id_cita FROM cita_programada WHERE fecha_hora = '2026-02-03 11:15:00'), (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0004'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Lucia Herrera'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-04-QTZ'), '2026-02-03', 'Primera vez', 'Control prenatal', 'Embarazo de 28 semanas', 'Sin complicaciones', 220.00),
((SELECT id_cita FROM cita_programada WHERE fecha_hora = '2026-02-12 16:30:00'), (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0006'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Patricia Molina'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-01-SMR'), '2026-02-12', 'Primera vez', 'Dolor lumbar', 'Dolor cronico', 'Fisioterapia recomendada', 200.00),
((SELECT id_cita FROM cita_programada WHERE fecha_hora = '2026-02-15 09:00:00'), (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Julio Ramirez'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-02-SMR'), '2026-02-15', 'Reconsulta', 'Ansiedad generalizada', 'Seguimiento psiquiatrico', 'Mejoria parcial', 150.00),
(NULL, (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0008'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Fernanda Diaz'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-03-SMR'), '2026-02-18', 'Referida', 'Infeccion urinaria', 'Referencia de medicina interna', 'Cultura pendiente', 160.00),
((SELECT id_cita FROM cita_programada WHERE fecha_hora = '2026-02-25 08:30:00'), (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Carmen Aguilar'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-05-SMR'), '2026-02-25', 'Primera vez', 'Hipertension arterial', 'Presion 150/95', 'Control de peso recomendado', 230.00),
((SELECT id_cita FROM cita_programada WHERE fecha_hora = '2026-03-01 10:00:00'), (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0019'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Pedro Alvarez'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-01-HUE'), '2026-03-01', 'Primera vez', 'Diabetes tipo 2', 'HbA1c 8.5%', 'Control glucemico', 240.00),
((SELECT id_cita FROM cita_programada WHERE fecha_hora = '2026-03-05 15:00:00'), (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0020'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Ana Maria Torres'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-03-HUE'), '2026-03-05', 'Primera vez', 'Asma bronquial', 'Episodio agudo', 'Inhalador salbutamol', 210.00),
(NULL, (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0024'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Beatriz Rojas'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-02-HUE'), '2026-03-09', 'Reconsulta', 'Control postparto', 'Sin complicaciones', 'Lactancia exclusiva', 180.00),
((SELECT id_cita FROM cita_programada WHERE fecha_hora = '2026-03-12 14:00:00'), (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0025'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Eduardo Salazar'), (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-04-HUE'), '2026-03-12', 'Primera vez', 'Trauma abdominal', 'Contusion sin fractura', 'Reposo de 7 dias', 230.00);

INSERT INTO receta (id_consulta, fecha, proxima_cita_fecha, id_clinica) VALUES
((SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001') AND fecha = '2026-01-20'), '2026-01-20', '2026-02-20', (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-01-QTZ')),
((SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0002') AND fecha = '2026-01-22'), '2026-01-22', '2026-02-22', (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-01-SMR')),
((SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0004') AND fecha = '2026-02-03'), '2026-02-03', '2026-03-03', (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-04-QTZ')),
((SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0006') AND fecha = '2026-02-12'), '2026-02-12', '2026-03-12', (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-01-SMR')),
((SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016') AND fecha = '2026-02-25'), '2026-02-25', '2026-03-25', (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-05-SMR')),
((SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0019') AND fecha = '2026-03-01'), '2026-03-01', '2026-04-01', (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-01-HUE')),
((SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0020') AND fecha = '2026-03-05'), '2026-03-05', '2026-04-05', (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-03-HUE')),
((SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0025') AND fecha = '2026-03-12'), '2026-03-12', '2026-04-12', (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-04-HUE')),
((SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007') AND fecha = '2026-02-15'), '2026-02-15', '2026-03-15', (SELECT id_clinica FROM clinica WHERE numero_clinica = 'CL-02-SMR')),
((SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003') AND fecha = '2026-02-01'), '2026-02-01', NULL, NULL);

INSERT INTO medicamento_recetado (id_receta, nombre_medicamento, dosis, duracion) VALUES
((SELECT id_receta FROM receta WHERE id_consulta = (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001') AND fecha = '2026-01-20')), 'Enalapril', '10 mg', '30 dias'),
((SELECT id_receta FROM receta WHERE id_consulta = (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001') AND fecha = '2026-01-20')), 'Amlodipina', '5 mg', '30 dias'),
((SELECT id_receta FROM receta WHERE id_consulta = (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0002') AND fecha = '2026-01-22')), 'Loratadina', '10 mg', '15 dias'),
((SELECT id_receta FROM receta WHERE id_consulta = (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0004') AND fecha = '2026-02-03')), 'Acido folico', '5 mg', '90 dias'),
((SELECT id_receta FROM receta WHERE id_consulta = (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0006') AND fecha = '2026-02-12')), 'Paracetamol', '500 mg', '7 dias'),
((SELECT id_receta FROM receta WHERE id_consulta = (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0006') AND fecha = '2026-02-12')), 'Tramadol', '50 mg', '5 dias'),
((SELECT id_receta FROM receta WHERE id_consulta = (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016') AND fecha = '2026-02-25')), 'Losartan', '50 mg', '30 dias'),
((SELECT id_receta FROM receta WHERE id_consulta = (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0019') AND fecha = '2026-03-01')), 'Metformina', '850 mg', '30 dias'),
((SELECT id_receta FROM receta WHERE id_consulta = (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0020') AND fecha = '2026-03-05')), 'Salbutamol', '200 mcg', '30 dias'),
((SELECT id_receta FROM receta WHERE id_consulta = (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0020') AND fecha = '2026-03-05')), 'Montelukast', '10 mg', '30 dias'),
((SELECT id_receta FROM receta WHERE id_consulta = (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0025') AND fecha = '2026-03-12')), 'Ibuprofeno', '400 mg', '7 dias'),
((SELECT id_receta FROM receta WHERE id_consulta = (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003') AND fecha = '2026-02-01')), 'Carbamazepina', '200 mg', '30 dias');
