-- 06_traslado_facturacion.sql
-- DML de traslados, facturacion, pagos y consumo

INSERT INTO traslado (id_paciente, id_medico_indica, fecha_hora, id_egreso_origen, id_unidad_origen, id_hospital_origen, origen_interno, id_ingreso_destino, id_unidad_destino, id_hospital_destino, destino_interno) VALUES
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Alejandro Morales'), '2026-01-15 10:00:00', (SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001') AND fecha_hora = '2026-01-10 08:30:00')), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Emergencias'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital Regional de Quetzaltenango'), TRUE, (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0013') AND fecha_hora = '2026-01-13 09:00:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Hospitalizacion'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital Regional de Quetzaltenango'), TRUE),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Julio Ramirez'), '2026-01-20 11:30:00', (SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007') AND fecha_hora = '2026-01-13 09:00:00')), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Hospitalizacion'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital Regional de Quetzaltenango'), TRUE, (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0015') AND fecha_hora = '2026-02-10 15:00:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Emergencias'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital Regional de Quetzaltenango'), TRUE),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0014'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Fernanda Diaz'), '2026-02-25 16:00:00', (SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0014') AND fecha_hora = '2026-02-10 15:00:00')), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Hospitalizacion'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital de Huehuetenango Occidental'), TRUE, (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0013') AND fecha_hora = '2026-01-13 09:00:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Cirugia'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital de Huehuetenango Occidental'), TRUE),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0012'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Elena Vargas'), '2026-01-22 10:45:00', (SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0012') AND fecha_hora = '2026-02-07 11:00:00')), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Cirugia'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital General San Marcos'), TRUE, (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0012') AND fecha_hora = '2026-02-07 11:00:00'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Hospitalizacion'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital General San Marcos'), TRUE),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0018'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Carmen Aguilar'), '2026-03-04 09:30:00', (SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0018') AND fecha_hora = '2026-03-02 10:30:00')), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Cirugia'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital de Huehuetenango Occidental'), FALSE, NULL, (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Emergencias'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital de Huehuetenango Occidental'), FALSE);

INSERT INTO factura (id_paciente, id_egreso, id_consulta, fecha_emision, descripcion, monto_total, estado_pago) VALUES
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001'), (SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001') AND fecha_hora = '2026-01-10 08:30:00')), NULL, '2026-01-16', 'Servicios de emergencia y hospitalizacion', 1250.00, 'Pagada'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003'), (SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003') AND fecha_hora = '2026-01-11 14:00:00')), NULL, '2026-01-14', 'Procedimiento quirurgico apendicectomia', 3200.00, 'En cuotas'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0005'), (SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0005') AND fecha_hora = '2026-01-12 22:15:00')), NULL, '2026-01-15', 'Emergencia traumatismo', 950.00, 'Pendiente'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007'), (SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007') AND fecha_hora = '2026-01-13 09:00:00')), NULL, '2026-01-21', 'Hospitalizacion medicina interna', 2100.00, 'Pagada'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0009'), NULL, (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0009') AND fecha = '2026-02-05'), '2026-02-05', 'Consulta pediatrica y medicamentos', 320.00, 'En cuotas'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0010'), NULL, (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0010') AND fecha = '2026-02-06'), '2026-02-06', 'Consulta pediatrica hospitalizacion', 450.00, 'Pagada'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0012'), (SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0012') AND fecha_hora = '2026-02-07 11:00:00')), NULL, '2026-02-15', 'Cirugia oncologica mamaria', 8500.00, 'En cuotas'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0014'), (SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0014') AND fecha_hora = '2026-02-10 15:00:00')), NULL, '2026-02-26', 'Neurologia y cuidados intermedios', 4800.00, 'En cuotas'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0018'), (SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0018') AND fecha_hora = '2026-03-02 10:30:00')), NULL, '2026-03-05', 'Cirugia ortopedica', 5800.00, 'Pagada'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0004'), NULL, (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0004') AND fecha = '2026-02-03'), '2026-02-03', 'Consulta ginecologica', 280.00, 'Pendiente'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016'), NULL, (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016') AND fecha = '2026-02-25'), '2026-02-25', 'Consulta cardiologia', 300.00, 'En cuotas'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0024'), (SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0024') AND fecha_hora = '2026-03-15 16:45:00')), NULL, '2026-03-17', 'Cirugia cesarea', 4200.00, 'Pagada'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0020'), NULL, (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0020') AND fecha = '2026-03-05'), '2026-03-05', 'Consulta neumologia', 380.00, 'En cuotas'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0023'), (SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0023') AND fecha_hora = '2026-03-10 12:00:00')), NULL, '2026-03-19', 'Oncologia hospitalizacion', 6200.00, 'En cuotas'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0025'), NULL, (SELECT id_consulta FROM consulta WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0025') AND fecha = '2026-03-12'), '2026-03-12', 'Consulta traumatologia', 350.00, 'Pendiente');

INSERT INTO detalle_factura (id_factura, concepto, monto) VALUES
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001')), 'Uso de camilla en emergencia', 150.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001')), 'Insumos utilizados', 300.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001')), 'Dias de hospitalizacion', 800.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003')), 'Procedimiento quirurgico', 2500.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003')), 'Uso de quirofano', 700.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0005')), 'Consulta medica', 350.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0005')), 'Insumos utilizados', 250.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007')), 'Dias de hospitalizacion', 1500.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0012')), 'Cirugia oncologica', 7000.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0012')), 'Insumos quirurgicos', 1500.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0014')), 'Neurologia', 3800.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0018')), 'Ortopedia', 5800.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0004')), 'Consulta ginecologica', 280.00);

INSERT INTO pago (id_factura, fecha_pago, numero_cuota, monto) VALUES
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003') AND estado_pago = 'En cuotas'), '2026-01-20', 1, 800.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003') AND estado_pago = 'En cuotas'), '2026-02-20', 2, 800.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003') AND estado_pago = 'En cuotas'), '2026-03-20', 3, 800.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003') AND estado_pago = 'En cuotas'), '2026-04-20', 4, 800.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0012') AND estado_pago = 'En cuotas'), '2026-02-16', 1, 1700.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0012') AND estado_pago = 'En cuotas'), '2026-03-16', 2, 1700.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0012') AND estado_pago = 'En cuotas'), '2026-04-16', 3, 1700.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0012') AND estado_pago = 'En cuotas'), '2026-05-16', 4, 1700.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0012') AND estado_pago = 'En cuotas'), '2026-06-16', 5, 1700.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016') AND estado_pago = 'En cuotas'), '2026-02-26', 1, 150.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016') AND estado_pago = 'En cuotas'), '2026-03-26', 2, 150.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0020') AND estado_pago = 'En cuotas'), '2026-03-06', 1, 190.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0014') AND estado_pago = 'En cuotas'), '2026-02-27', 1, 960.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0023') AND estado_pago = 'En cuotas'), '2026-03-20', 1, 1240.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0023') AND estado_pago = 'En cuotas'), '2026-04-20', 2, 1240.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0023') AND estado_pago = 'En cuotas'), '2026-05-20', 3, 1240.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0023') AND estado_pago = 'En cuotas'), '2026-06-20', 4, 1240.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0023') AND estado_pago = 'En cuotas'), '2026-07-20', 5, 1240.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001') AND estado_pago = 'Pagada'), '2026-01-16', 1, 1250.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007') AND estado_pago = 'Pagada'), '2026-01-21', 1, 2100.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0018') AND estado_pago = 'Pagada'), '2026-03-05', 1, 5800.00),
((SELECT id_factura FROM factura WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0024') AND estado_pago = 'Pagada'), '2026-03-17', 1, 4200.00);

INSERT INTO consumo_insumo (id_ingreso, id_insumo, cantidad) VALUES
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001') AND fecha_hora = '2026-01-10 08:30:00'), (SELECT id_insumo FROM insumo WHERE nombre = 'Jeringa 10 ml'), 5),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001') AND fecha_hora = '2026-01-10 08:30:00'), (SELECT id_insumo FROM insumo WHERE nombre = 'Cateter venoso'), 1),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007') AND fecha_hora = '2026-01-13 09:00:00'), (SELECT id_insumo FROM insumo WHERE nombre = 'Suero fisiologico'), 3),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0012') AND fecha_hora = '2026-02-07 11:00:00'), (SELECT id_insumo FROM insumo WHERE nombre = 'Guantes quirurgicos'), 8),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0018') AND fecha_hora = '2026-03-02 10:30:00'), (SELECT id_insumo FROM insumo WHERE nombre = 'Bisturi descartable'), 2),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0025') AND fecha_hora = '2026-04-02 09:10:00'), (SELECT id_insumo FROM insumo WHERE nombre = 'Gasa esteril'), 10);
