-- 07_historia_agendamiento.sql
-- DML de historia clinica, exploracion y agendamiento

INSERT INTO historia_clinica (id_paciente, sexo, edad, estado_civil, religion, ocupacion, lugar_nacimiento, lugar_residencia, antecedentes_heredofamiliares, antecedentes_personales_no_patologicos, antecedentes_patologicos, padecimiento_actual, interrogatorio_aparatos_sistemas, sintomas_generales_terapeutica, estudios_previos) VALUES
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001'), 'Masculino', 35, 'Casado', 'Catolica', 'Comerciante', 'Quetzaltenango', 'Quetzaltenango', 'Padre con hipertension', 'No alergias conocidas', 'Hipertension', 'Dolor toracico de 2 horas', 'Dolor opresivo retroesternal', 'Nausea y sudoracion', 'Electrocardiograma con ST elevado'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0002'), 'Femenino', 40, 'Casado', 'Catolica', 'Maestra', 'San Marcos', 'San Marcos', NULL, 'Vacunada completa', 'Rinitis alergica', 'Estornudos y congestion nasal', 'Rinorrea clara bilateral', 'Prurito ocular leve', 'Prueba de alergia pendiente'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003'), 'Masculino', 47, 'Soltero', 'Catolica', 'Agricultor', 'Huehuetenango', 'Huehuetenango', 'Madre con diabetes', 'Fumador social', 'Apendicitis', 'Dolor abdominal en fosa iliaca derecha', 'Nausea y anorexia', 'Fiebre 38.5 C', 'Ultrasonido con apendice engrosado'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0005'), 'Masculino', 61, 'Viudo', 'Catolica', 'Jubilado', 'Quetzaltenango', 'Quetzaltenango', 'Hermano fallecido por infarto', 'Hipertension controlada', 'Traumatismo craneal', 'Caida de escalera con golpe en cabeza', 'Cefalea intensa y mareo', 'Perdida breve de conciencia', 'Tomografia sin hemorragia'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0009'), 'Masculino', 18, 'Soltero', NULL, 'Estudiante', 'Quetzaltenango', 'Quetzaltenango', NULL, 'Asma controlada', 'Fiebre alta y convulsion', 'Convulsion tonico-clonica', 'Febricula postictal', 'Dolor muscular generalizado', 'Electroencefalograma normal'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0014'), 'Femenino', 39, 'Casado', 'Catolica', 'Contadora', 'San Marcos', 'San Marcos', 'Tia con cancer de mama', 'Hipotiroidismo', 'ACV isquemico', 'Dificultad para hablar', 'Hemiparesia derecha', 'Cefalea leve', 'Tomografia con infarto'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016'), 'Femenino', 37, 'Casado', 'Catolica', 'Ama de casa', 'Totonicapan', 'Totonicapan', 'Madre con diabetes', 'Sin antecedentes patologicos', 'Pancreatitis', 'Dolor epigastrico intenso', 'Nausea y vomito', 'Fiebre 39 C', 'Amilasa y lipasa elevadas'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0024'), 'Femenino', 38, 'Casado', 'Catolica', 'Comerciante', 'Totonicapan', 'Totonicapan', NULL, 'Sin antecedentes', 'Cesarea programada', 'Embarazo a termino', 'Contracciones irregulares', 'Movimientos fetales normales', 'Perfil biofisico normal');

INSERT INTO exploracion_fisica (id_historia, signos_vitales, exploracion_general, cabeza, cuello, torax, abdomen, extremidades, columna_vertebral, cavidades) VALUES
((SELECT id_historia FROM historia_clinica WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001')),
'TA 160/100 FC 98 FR 20 T 36.5', 'Paciente en regular estado general, ansioso', 'Sin alteraciones', 'Sin adenopatias', 'Ruidos cardiacos aumentados, soplo sistolico', 'Blando no doloroso', 'Sin edemas', 'Sin alteraciones', NULL),
((SELECT id_historia FROM historia_clinica WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0002')),
'TA 120/75 FC 72 FR 18 T 36.8', 'Paciente en buen estado', 'Sin alteraciones', 'Sin adenopatias', 'Campos pulmonares limpios', 'Blando no doloroso', 'Sin edemas', 'Sin alteraciones', NULL),
((SELECT id_historia FROM historia_clinica WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003')),
'TA 130/85 FC 88 FR 22 T 37.8', 'Paciente afebril, alerta', 'Sin alteraciones', 'Sin adenopatias', 'Ruidos respiratorios normales', 'Dolor en fosa iliaca derecha con defensa', 'Sin edemas', 'Sin alteraciones', NULL),
((SELECT id_historia FROM historia_clinica WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0005')),
'TA 140/90 FC 85 FR 20 T 37.0', 'Paciente confuso, orientado parcialmente', 'Contusion parietal derecha', 'Rango de movimiento limitado por dolor', 'Ruidos respiratorios disminuidos', 'Blando no doloroso', 'Sin edemas', 'Sin alteraciones', NULL),
((SELECT id_historia FROM historia_clinica WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0009')),
'TA 110/70 FC 100 FR 24 T 38.2', 'Paciente postictal, somnoliento', 'Sin alteraciones', 'Sin adenopatias', 'Ruidos respiratorios normales', 'Blando no doloroso', 'Sin edemas', 'Sin alteraciones', NULL),
((SELECT id_historia FROM historia_clinica WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0014')),
'TA 150/95 FC 78 FR 18 T 36.6', 'Paciente con dificultad para hablar', 'Asimetria facial leve derecha', 'Rigidez cervical leve', 'Ruidos respiratorios normales', 'Blando no doloroso', 'Fuerza disminuida derecha', 'Sin alteraciones', NULL),
((SELECT id_historia FROM historia_clinica WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016')),
'TA 115/80 FC 92 FR 20 T 39.0', 'Paciente en regular estado', 'Sin alteraciones', 'Sin adenopatias', 'Ruidos respiratorios normales', 'Dolor epigastrico profundo', 'Sin edemas', 'Sin alteraciones', NULL),
((SELECT id_historia FROM historia_clinica WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0024')),
'TA 120/80 FC 82 FR 18 T 36.7', 'Paciente embarazada en buen estado', 'Sin alteraciones', 'Sin adenopatias', 'Ruidos respiratorios normales', 'Utero a termino, presentacion cefalica', 'Sin edemas', 'Sin alteraciones', NULL);

INSERT INTO agendamiento_quirurgico (id_paciente, id_historia, id_medico_cirujano, id_hospital, caracter, tipo_procedimiento, tiempo_estimado, tipo_anestesia, fecha_hora_solicitud, estado, motivo_rechazo) VALUES
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001'), (SELECT id_historia FROM historia_clinica WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001')), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Roberto Castillo'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital Regional de Quetzaltenango'), 'Programado', 'Bypass coronario', '04:30:00', 'General', '2026-01-18 08:00:00', 'Aprobado', NULL),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0002'), (SELECT id_historia FROM historia_clinica WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0002')), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Elena Vargas'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital General San Marcos'), 'Programado', 'Mastectomia radical', '03:00:00', 'General', '2026-01-25 09:00:00', 'Pendiente', NULL),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003'), (SELECT id_historia FROM historia_clinica WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003')), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Carlos Mendez'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital Regional de Quetzaltenango'), 'Urgente', 'Apendicectomia laparoscopica', '01:30:00', 'General', '2026-01-11 13:00:00', 'Aprobado', NULL),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0005'), (SELECT id_historia FROM historia_clinica WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0005')), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Lucia Herrera'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital de Huehuetenango Occidental'), 'Programado', 'Craneotomia evacuadora', '05:00:00', 'General', '2026-01-14 10:00:00', 'Pendiente', NULL),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007'), (SELECT id_historia FROM historia_clinica WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007')), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Julio Ramirez'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital General San Marcos'), 'Programado', 'Neurocirugia descompresiva', '04:00:00', 'General', '2026-01-21 09:00:00', 'Aprobado', NULL),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0014'), (SELECT id_historia FROM historia_clinica WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0014')), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Fernanda Diaz'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital de Huehuetenango Occidental'), 'Programado', 'Trombectomia mecánica', '03:30:00', 'General', '2026-02-11 08:00:00', 'Rechazado', 'Paciente no apto para anestesia general'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016'), (SELECT id_historia FROM historia_clinica WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016')), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Mario Gutierrez'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital Regional de Quetzaltenango'), 'Urgente', 'Pancreatectomia parcial', '03:00:00', 'General', '2026-02-11 14:00:00', 'Aprobado', NULL),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0024'), (SELECT id_historia FROM historia_clinica WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0024')), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Gabriela Luna'), (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital Regional de Quetzaltenango'), 'Programado', 'Cesarea', '01:00:00', 'Regional', '2026-03-16 07:00:00', 'Aprobado', NULL);
