-- 08_cirugia.sql
-- DML de cirugia, consentimiento y chequeo preanestesico

INSERT INTO ingreso (id_paciente, id_unidad_medica, id_medico, id_recurso, fecha_hora, motivo_ingreso, diagnostico_presuntivo) VALUES
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001'), (SELECT id_unidad_medica FROM unidad_medica WHERE id_hospital = (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital Regional de Quetzaltenango') AND tipo_unidad = 'Cirugia'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Roberto Castillo'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'QF-QTZ-01'), '2026-01-18 08:00:00', 'Bypass coronario programado', 'Cardiopatia isquemica'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003'), (SELECT id_unidad_medica FROM unidad_medica WHERE id_hospital = (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital Regional de Quetzaltenango') AND tipo_unidad = 'Cirugia'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Carlos Mendez'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'QF-QTZ-02'), '2026-01-11 14:00:00', 'Apendicitis aguda urgente', 'Apendicitis complicada'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007'), (SELECT id_unidad_medica FROM unidad_medica WHERE id_hospital = (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital General San Marcos') AND tipo_unidad = 'Cirugia'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Julio Ramirez'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'QF-SMR-01'), '2026-01-21 10:00:00', 'Neurocirugia descompresiva', 'Trauma craneoencefalico'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016'), (SELECT id_unidad_medica FROM unidad_medica WHERE id_hospital = (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital Regional de Quetzaltenango') AND tipo_unidad = 'Cirugia'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Mario Gutierrez'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'QF-QTZ-03'), '2026-02-11 15:00:00', 'Pancreatectomia urgente', 'Pancreatitis necrotizante'),
((SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0024'), (SELECT id_unidad_medica FROM unidad_medica WHERE id_hospital = (SELECT id_hospital FROM hospital WHERE nombre = 'Hospital Regional de Quetzaltenango') AND tipo_unidad = 'Cirugia'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Gabriela Luna'), (SELECT id_recurso FROM recurso_asignable WHERE codigo = 'QF-QTZ-04'), '2026-03-16 08:00:00', 'Cesarea programada', 'Embarazo a termino');

INSERT INTO egreso (id_ingreso, id_unidad_medica, id_medico, fecha_hora, diagnostico_principal, motivo_egreso, codigo_egreso, egreso_sin_consentimiento) VALUES
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003') AND motivo_ingreso = 'Apendicitis aguda urgente'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Cirugia'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Carlos Mendez'), '2026-01-13 09:00:00', 'Apendicitis complicada resuelta', 'Alta quirurgica', 'Vivo', FALSE),
((SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0024') AND motivo_ingreso = 'Cesarea programada'), (SELECT id_unidad_medica FROM unidad_medica WHERE tipo_unidad = 'Cirugia'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Gabriela Luna'), '2026-03-16 12:00:00', 'Embarazo a termino resuelto por cesarea', 'Alta postparto', 'Parto', FALSE);

INSERT INTO cirugia (id_agendamiento, id_medico_cirujano, id_medico_anestesista, id_ingreso, id_egreso, fecha_hora_inicio, fecha_hora_fin) VALUES
((SELECT id_agendamiento FROM agendamiento_quirurgico WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001')), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Roberto Castillo'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Julio Ramirez'), (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0001') AND motivo_ingreso = 'Bypass coronario programado'), NULL, '2026-01-18 09:30:00', '2026-01-18 13:45:00'),
((SELECT id_agendamiento FROM agendamiento_quirurgico WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003')), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Carlos Mendez'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Mario Gutierrez'), (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003') AND motivo_ingreso = 'Apendicitis aguda urgente'), (SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0003') AND motivo_ingreso = 'Apendicitis aguda urgente')), '2026-01-11 15:00:00', '2026-01-11 16:15:00'),
((SELECT id_agendamiento FROM agendamiento_quirurgico WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007')), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Julio Ramirez'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Eduardo Salazar'), (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0007') AND motivo_ingreso = 'Neurocirugia descompresiva'), NULL, '2026-01-21 11:00:00', '2026-01-21 14:30:00'),
((SELECT id_agendamiento FROM agendamiento_quirurgico WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016')), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Mario Gutierrez'), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Ana Maria Torres'), (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0016') AND motivo_ingreso = 'Pancreatectomia urgente'), NULL, '2026-02-11 16:00:00', '2026-02-11 18:30:00'),
((SELECT id_agendamiento FROM agendamiento_quirurgico WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0024')), (SELECT id_medico FROM medico WHERE nombre = 'Dra. Gabriela Luna'), (SELECT id_medico FROM medico WHERE nombre = 'Dr. Pedro Alvarez'), (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0024') AND motivo_ingreso = 'Cesarea programada'), (SELECT id_egreso FROM egreso WHERE id_ingreso = (SELECT id_ingreso FROM ingreso WHERE id_paciente = (SELECT id_paciente FROM paciente WHERE no_expediente = 'EXP-0024') AND motivo_ingreso = 'Cesarea programada')), '2026-03-16 09:00:00', '2026-03-16 09:45:00');

INSERT INTO consentimiento_informado (id_cirugia, nombre_procedimiento, objetivo, caracteristicas, riesgos, firma_medico, firma_paciente_o_representante, fecha) VALUES
((SELECT id_cirugia FROM cirugia WHERE id_medico_cirujano = (SELECT id_medico FROM medico WHERE nombre = 'Dr. Roberto Castillo')), 'Bypass coronario', 'Restaurar flujo sanguineo al corazon', 'Procedimiento con bomba de circulacion extracorporea', 'Infeccion, sangrado, arritmias', 'Dr. Roberto Castillo', 'Juan Carlos Perez Gomez', '2026-01-17'),
((SELECT id_cirugia FROM cirugia WHERE id_medico_cirujano = (SELECT id_medico FROM medico WHERE nombre = 'Dr. Carlos Mendez')), 'Apendicectomia laparoscopica', 'Extirpar apendice inflamado', 'Cirugia minimamente invasiva con 3 incisiones', 'Infeccion, sangrado, lesion intestinal', 'Dr. Carlos Mendez', 'Luis Alberto Herrera Diaz', '2026-01-11'),
((SELECT id_cirugia FROM cirugia WHERE id_medico_cirujano = (SELECT id_medico FROM medico WHERE nombre = 'Dr. Julio Ramirez')), 'Neurocirugia descompresiva', 'Aliviar presion intracraneal', 'Craneotomia con evacuacion de hematoma', 'Deficit neurologico, infeccion, sangrado', 'Dr. Julio Ramirez', 'Roberto Jose Solis Martinez', '2026-01-20'),
((SELECT id_cirugia FROM cirugia WHERE id_medico_cirujano = (SELECT id_medico FROM medico WHERE nombre = 'Dr. Mario Gutierrez')), 'Pancreatectomia parcial', 'Reseccion de tejido necrotico', 'Reseccion de cola del pancreas', 'Fistula pancreatica, infeccion, diabetes', 'Dr. Mario Gutierrez', 'Lucia Fernanda Morales Diaz', '2026-02-10'),
((SELECT id_cirugia FROM cirugia WHERE id_medico_cirujano = (SELECT id_medico FROM medico WHERE nombre = 'Dra. Gabriela Luna')), 'Cesarea', 'Extraccion del producto por via abdominal', 'Incision suprapubica transversa', 'Hemorragia, infeccion, trombosis', 'Dra. Gabriela Luna', 'Andres Felipe Castro Morales', '2026-03-15');

INSERT INTO chequeo_preanestesico (id_cirugia, clasificacion_asa, id_medico_clasifica, plan_anestesia, id_medico_anestesista) VALUES
((SELECT id_cirugia FROM cirugia WHERE id_medico_cirujano = (SELECT id_medico FROM medico WHERE nombre = 'Dr. Roberto Castillo')), 'ASA III', (SELECT id_medico FROM medico WHERE nombre = 'Dr. Alejandro Morales'), 'Anestesia general con intubacion orotraqueal, monitorizacion invasiva', (SELECT id_medico FROM medico WHERE nombre = 'Dr. Julio Ramirez')),
((SELECT id_cirugia FROM cirugia WHERE id_medico_cirujano = (SELECT id_medico FROM medico WHERE nombre = 'Dr. Carlos Mendez')), 'ASA II', (SELECT id_medico FROM medico WHERE nombre = 'Dr. Carlos Mendez'), 'Anestesia general con intubacion, analgesia multimodal', (SELECT id_medico FROM medico WHERE nombre = 'Dr. Mario Gutierrez')),
((SELECT id_cirugia FROM cirugia WHERE id_medico_cirujano = (SELECT id_medico FROM medico WHERE nombre = 'Dr. Julio Ramirez')), 'ASA IV', (SELECT id_medico FROM medico WHERE nombre = 'Dra. Elena Vargas'), 'Anestesia general con monitorizacion intensiva, manejo de presion intracraneal', (SELECT id_medico FROM medico WHERE nombre = 'Dr. Eduardo Salazar')),
((SELECT id_cirugia FROM cirugia WHERE id_medico_cirujano = (SELECT id_medico FROM medico WHERE nombre = 'Dr. Mario Gutierrez')), 'ASA III', (SELECT id_medico FROM medico WHERE nombre = 'Dr. Mario Gutierrez'), 'Anestesia general con manejo hemodinamico estricto', (SELECT id_medico FROM medico WHERE nombre = 'Dra. Ana Maria Torres')),
((SELECT id_cirugia FROM cirugia WHERE id_medico_cirujano = (SELECT id_medico FROM medico WHERE nombre = 'Dra. Gabriela Luna')), 'ASA I', (SELECT id_medico FROM medico WHERE nombre = 'Dra. Gabriela Luna'), 'Anestesia regional subaracnoidea, sedacion consciente', (SELECT id_medico FROM medico WHERE nombre = 'Dr. Pedro Alvarez'));
